# Generated by Django 4.1.4 on 2022-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='img',
        ),
        migrations.RemoveField(
            model_name='player',
            name='img',
        ),
        migrations.AddField(
            model_name='country',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/countries'),
        ),
        migrations.AddField(
            model_name='player',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%team'),
        ),
        migrations.AddField(
            model_name='team',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%name'),
        ),
    ]
