# Generated by Django 4.1.4 on 2022-12-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_country_img_remove_player_img_country_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
