# Generated by Django 4.1.4 on 2022-12-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='profile',
        ),
    ]
