# Generated by Django 4.1.4 on 2022-12-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
