# Generated by Django 4.1.4 on 2022-12-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AddField(
            model_name='country',
            name='profile',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
