# Generated by Django 4.1.4 on 2022-12-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_rename_imagen_country_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='profile',
        ),
    ]
