# Generated by Django 4.1.4 on 2022-12-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_country_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.DateTimeField(max_length=300),
        ),
        migrations.AlterField(
            model_name='player',
            name='sing_date',
            field=models.DateTimeField(max_length=300),
        ),
    ]
